# rofi 安装说明文档
include::../../../doc/base.adoc[]

https://github.com/davatorium/rofi[官方文档]


## 问题记录

### 原生wayland的支持

目前有一个仓库支持wayland的： https://aur.archlinux.org/packages/rofi-lbonn-wayland-git[rofi-lbonn-wayland-git]

对应的 `Archlinux` 的包是 `rofi-wayland` 。

[#rofi-focus]
### rofi 焦点问题

使用的包是： https://archlinux.org/packages/extra/x86_64/rofi/[rofi]

启动 `rofi` 总是没有焦点，不能直接输入或者选中，需要鼠标移动到它上面才可以

有时候启动 `rofi` 后，输入后界面会跑到另一个显示器上。

有时候启动 `rofi` 后程序的宽度不一样，并且不能输入，鼠标移动上去没反应，也不能点击。

尝试修改Hyprland的窗口规则也不能解决问题：

[source]
----
windowrulev2 = center 1,class:^(Rofi)$
windowrulev2 = stayfocused,class:^(Rofi)$
windowrulev2 = forceinput,class:^(Rofi)$
----

使用 `rofi-wayland` 包后，焦点的问题解决了。应该是 `rofi` 在 `xwayland` 上有问题。

还是期望官方可以早日支持 `wayland` 。

### `'calc.so' does not match`

更新 `rofi` 后运行 `rofi` 失败，在终端运行 `rofi` 报错：`ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007`。

这个是因为使用的是 https://archlinux.org/packages/extra/x86_64/rofi-wayland/[rofi-wayland] 包，而 `rofi-calc` 是官方仓库的包，它是适配官方仓库的 `rofi` 的。

官方仓库的 `rofi` 是不支持 `wayland` 的。

https://github.com/svenstaro/rofi-calc/issues?q=abi+version+of+plugin[rofi-calc] 仓库里可以看到类似的问题。

大部分的提到的解决方式是重新源码编译 `rofi-calc` 包。

但是官方仓库的 `rofi-calc` 是二进制包，所以只能使用 `rofi-calc-git` 包。

后面我发现报这个报错并不是导致 `rofi` 启动失败的原因，这个报错只会导致不能使用 `rofi-calc` 的功能， `rofi` 是可以正常启动的。

[source,console]
====
❯ rofi -show calc -modi calc -no-show-match -no-sort

(process:2443): Rofi-WARNING **: 16:40:34.434: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007
❯ rofi -show-icons -show combi -combi-modes "drun,window,run,ssh" -modes combi

(process:2503): Rofi-WARNING **: 16:41:10.464: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007
====

第一个命令可以运行 `rofi` ，但是提示错误： `Mode calc is not found` 。
第二各命令可以运行 `rofi` ，并且可以运行程序。

安装 `rofi-calc-git` 包后，再次运行 `rofi` 就没有这个报错了。

考虑到我没怎么使用 `rofi-calc` 的功能，所以后面我也就没有部署它。


### rofi 运行异常 `bus error`

[source,console]
====

❯ rofi -show-icons -show combi -combi-modes "drun,window,run,ssh" -modes combi
zsh: bus error (core dumped)  rofi -show-icons -show combi -combi-modes "drun,window,run,ssh" -modes combi

====

目前不知道具体原因，重启电脑可以解决。