# https://wiki.archlinuxcn.org/wiki/Zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/lib/constant.zsh"
source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/lib/os.zsh"


# source ~/.config/zsh/zshrc.d 目录下的所有 zsh 配置
source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zshrc.d/source.zsh"


# zsh-syntax-highlighting 配置
# NOTE: 这个必须是最后一行，https://github.com/zsh-users/zsh-syntax-highlighting?tab=readme-ov-file#why-must-zsh-syntax-highlightingzsh-be-sourced-at-the-end-of-the-zshrc-file
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets pattern regexp cursor root line)
